// KasaiRaito Studios All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace  WarriorGameplayTags
{
	/** INPUT TAGS **/
		//Movement
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
		//Equip
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
		//Attack
			//Light
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
			//Heavy
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	
	/** Player TAGS **/
		//Equip Axe ABILITY
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
		//Attack
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
		//Weapon
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
		//Equip Axe EVENTS
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Events_Equip_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Events_Unequip_Axe);
		//Status
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
		//SetByCaller
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);
	
	/** Enemy TAGS **/
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/** Shared TAGS **/
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	
}
