// KasaiRaito Studios All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace  WarriorGameplayTags
{
	/** INPUT TAGS **/
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	/** Player TAGS **/
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Events_Equip_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Events_Unequip_Axe);
}
