// KasaiRaito Studios All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace  WarriorGameplayTags
{
	/** INPUT TAGS **/
		//Movement
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
		//Equip
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
		//Attack
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	
	/** Player TAGS **/
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);

	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Events_Equip_Axe);
	PROYECTHADES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Events_Unequip_Axe);
	
}
